packages:
  - 'packages/*'
  - 'apps/*'
  - '!**/test/**'
allowBuilds:
  '@uni-helper/unocss-preset-uni': set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
